services:
  # The API Backend Service
  - type: web
    name: opengym-api
    runtime: docker
    dockerfilePath: api/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: RP_ID
        sync: false
      - key: ORIGIN
        sync: false
    disk:
      name: opengym-data
      mountPath: /app/data
      sizeGB: 1

  # The Frontend Static / Web Service 
  - type: web
    name: opengym-web
    runtime: docker
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: PORT
        value: 80
